import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import NavBar from "@/components/NavBar";
import Hero from "@/components/Hero";
import Features from "@/components/Features";
import Prices from "@/components/Prices";
import Faqs from "@/components/Faqs";
import Reviews from "@/components/Reviews";

export default function Home() {
  return (
    <>
      <Head>
        <title>MoshelSwap</title>
        <meta name="description" content="Generated by create next app"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>

      <main className="bg-black text-white">
        <div className="top">
            <div className="left flex-1 md:flex-[6]">
              {/*Navigation*/}
              <NavBar/>

              {/*Hero*/}
              <Hero/>
            </div>

            {/*Image*/}
            <div className="right flex-1 md:flex-[4]">
              <div className="pt-7 flex justify-end items-center">
                <a href="#" className="connect-btn"> Connect Wallet </a>
              </div>

              <div>
                <Image src="/img/vintage.png" alt="vintage NFT" width={100} height={100} layout="responsive"/>
              </div>
            </div>
        </div>

        <Features/>

        <Prices/>

        <Faqs />

        <Reviews/>

        <Calculator />

        <div className="cta">
          <Image src="/img/vr.png" width={100} height={100}/>

          <div className="flex justify-center items-center pb-2">
            <p>copyrights &copy; 2023 MoshelSwap</p>
          </div>
        </div>

      </main>
    </>
  )
}
