import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'

export default function Home() {
  return (
    <>
      <Head>
        <title>MoshelSwap</title>
        <meta name="description" content="Generated by create next app"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>

      <main className="bg-black text-white">
        <div className="top">

            <div className="left flex-1 md:flex-[6]">
              {/*Navigation*/}
              <nav className="nav mt-7">
                <div className="wrapper">
                  <div className="m-nav flex justify-between items-center">
                    <img src="/img/logo_main.png" alt="logo" className="logo"/>
                    <div className="toggle">
                      <div></div>
                      <div></div>
                      <div></div>
                    </div>

                    <div className="d-links">
                      <a href="#" className="link-item"> Home </a>
                      <a href="#" className="link-item"> How it works </a>
                      <a href="#" className="link-item"> Roadmap </a>
                    </div>
                  </div>
                </div>
              </nav>

              {/*Hero*/}
              <section className="mb-14">
                <div className="wrapper">
                  <h1 className="hero-title relative z-50">
                    Exchange your BTC, ETH, USDT, BNB, and BUSD with <span className="highlight">Ease</span>
                  </h1>

                  <p className="subtitle">
                    At MoshelSwap, you are one click away from converting your digital assets into ₦NGN. Our team has
                    been
                    trading digital assets professionally since 2015 and we offer the best rates.
                  </p>

                  <div className="flex justify-center lg:justify-start items-center font-exo-bold">
                    <button className="chat-btn"> Chat on WhatsApp</button>
                  </div>
                </div>
              </section>
            </div>

            {/*Image*/}
            <div className="right flex-1 md:flex-[4]">
              <div className="pt-7 flex justify-end items-center">
                <a href="#" className="connect-btn"> Connect Wallet </a>
              </div>

              <div>
                <Image src="/img/vintage.png" alt="vintage NFT" width={100} height={100} layout="responsive"/>
              </div>
            </div>

        </div>
      </main>
    </>
  )
}
